-- =========================
-- Migration v4: Account Management Upgrade
-- =========================

-- 0. Sử dụng database
USE ComputerSpace;

-- 1. Bảng reset password token
CREATE TABLE IF NOT EXISTS RESET_TOKEN (
    MaToken INT AUTO_INCREMENT PRIMARY KEY,
    MaTK INT NOT NULL,
    Token VARCHAR(255) NOT NULL UNIQUE,
    NgayHetHan DATETIME NOT NULL,
    DaSuDung TINYINT DEFAULT 0,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaTK) REFERENCES TAI_KHOAN(MaTK) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 2. Bảng xác thực email token
CREATE TABLE IF NOT EXISTS VERIFICATION_TOKEN (
    MaToken INT AUTO_INCREMENT PRIMARY KEY,
    MaTK INT NOT NULL,
    Token VARCHAR(255) NOT NULL UNIQUE,
    NgayHetHan DATETIME NOT NULL,
    DaSuDung TINYINT DEFAULT 0,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaTK) REFERENCES TAI_KHOAN(MaTK) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 3. Mở rộng bảng KHACH_HANG
ALTER TABLE KHACH_HANG
    ADD COLUMN DaXacThucEmail TINYINT DEFAULT 0,
    ADD COLUMN AnhDaiDien VARCHAR(255) NULL;

-- 4. Mở rộng bảng TAI_KHOAN
ALTER TABLE TAI_KHOAN
    ADD COLUMN DaBat2FA TINYINT DEFAULT 0,
    ADD COLUMN Secret2FA VARCHAR(255) NULL,
    ADD COLUMN YeuCauXoaNgay DATETIME NULL,
    ADD COLUMN NgayDoiMatKhau DATETIME DEFAULT CURRENT_TIMESTAMP;

-- 5. Bảng audit log
CREATE TABLE IF NOT EXISTS AUDIT_LOG (
    MaLog INT AUTO_INCREMENT PRIMARY KEY,
    MaTK INT NOT NULL,
    HanhDong VARCHAR(50) NOT NULL,
    ChiTiet TEXT,
    IpAddress VARCHAR(45),
    ThoiGian DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaTK) REFERENCES TAI_KHOAN(MaTK) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE INDEX IDX_AUDIT_LOG_MaTK ON AUDIT_LOG(MaTK);
CREATE INDEX IDX_AUDIT_LOG_ThoiGian ON AUDIT_LOG(ThoiGian);

-- 6. Bảng user session
CREATE TABLE IF NOT EXISTS USER_SESSION (
    MaSession INT AUTO_INCREMENT PRIMARY KEY,
    MaTK INT NOT NULL,
    SessionToken VARCHAR(255) NOT NULL UNIQUE,
    IpAddress VARCHAR(45),
    UserAgent TEXT,
    ThoiGianTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    ThoiGianHetHan DATETIME NOT NULL,
    FOREIGN KEY (MaTK) REFERENCES TAI_KHOAN(MaTK) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE INDEX IDX_USER_SESSION_MaTK ON USER_SESSION(MaTK);

-- 7. Bảng password history
CREATE TABLE IF NOT EXISTS PASSWORD_HISTORY (
    MaLichSu INT AUTO_INCREMENT PRIMARY KEY,
    MaTK INT NOT NULL,
    MatKhauHash VARCHAR(255) NOT NULL,
    NgayDoi DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaTK) REFERENCES TAI_KHOAN(MaTK) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE INDEX IDX_PASSWORD_HISTORY_MaTK ON PASSWORD_HISTORY(MaTK);

